version: "3.1"
services:
  postgres-naughts-and-crosses:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - 54321:5432
